### ISSUE TITLE
Converting features to nxn matrix

### ISSUE THREAD

**Issue by utkarsh0902311047** [mahbubhimel/Intrusion-Detection-System-Using-Convolutional-Neural-Network#1]
Hi,
Thank you for providing your code.
May I ask according to the paper where are you converting the features into nxn matrix?

Thank you
Utkarsh

**Comment by mahbubhimel** [comment]
I have converted the features into numbers with heading "working with
validation data". Then i have re-shaped the matrix to feed into the model.
Hope it helps.

Regards,
Mahbub-E-Sobhani

**Comment by utkarsh0902311047** [comment]
Yeah I understand that. But what I couldn't get is that paper mentions the input to CNN needs to be nxn matrix. But you reshaped them to (?, 83,1). So where do you use nxn matrix?
Please advice

**Comment by mahbubhimel** [comment]
the input shape to feed into cnn layer has to be (?,?,1). I have converted
the matrix n x n inside working with validation data. you can try to feed
data without using np.reshape to see what happens. This is a 1D CNN model
that is why I had to reshape the nxn matrix.

Regards,
Mahbub-E-Sobhani
