### ISSUE TITLE
Multi-class classification

### ISSUE THREAD

**Issue by redbull286** [mahbubhimel/Intrusion-Detection-System-Using-Convolutional-Neural-Network#2]
Hi,
May I ask you a question about the code where is the model for multi-class classification?
I was trying to read your paper but I can find a way to change your code.
Thank you
Duy

**Comment by mahbubhimel** [comment]
I did not push the code of multiclass classification.

**Comment by DuyMTA** [comment]
Thank you for your response
When I change your model for multi-class classification, I remove some Drop layers after the CNN layer and keep only one Drop layer between Flat and Dense
Then I change your preprocessing function, I keep other features not only from duration to hot
I get 93.98% in the validate-set and 89.03% in the test-set
Can you rerun your program and check your result
Thank you

**Comment by mahbubhimel** [comment]
Thank you for your email.
If you have got 89.03% in the test set, then it's really incredible. I just
kept the same model but reduced some data by determining from feature
co-relations and found out the result mentioned in the paper. I am just
excited to see your work on multiclass classification. If there is no
problem can you please share your code with me?
Regards,
Mahbub E Sobhani
